from enum import Enum


class UILayer(Enum):
    LABEL_BACKGROUND = 0
    LABEL_CONTENT = 1

    BACKGROUND = 10
    BACKGROUND_DECORATION = 11

    CONTENT_BACKGROUND = 12
    CONTENT = 13
    CONTENT_INTERACTION = 14
