from enum import Enum


class UILayer(Enum):
    LABEL_BACKGROUND = 0
    LABEL_CONTENT = 1

    BACKGROUND = 10
    BACKGROUND_DECORATION = 11

    CONTENT_BACKGROUND = 12
    CONTENT = 13
    CONTENT_BADGE_BACKGROUND = 14
    CONTENT_BADGE_FOREGROUND = 15
    CONTENT_INTERACTION = 16

    MODAL_SHADOW = 20
    MODAL_BACKGROUND = 21

    MODAL_CONTENT_BACKGROUND = 22
    MODAL_CONTENT = 23
    MODAL_CONTENT_INTERACTION = 24
