name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Check out the branch
      uses: actions/checkout@v3

    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1

    - name: Set Up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Display Python Version
      run: python -c "import sys; print(sys.version)"

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Upgrade Pip
      run: |
        make upgrade-pip

    - name: Install Dependencies
      run: |
        make install-dev

    - name: Cache Resolved Dependencies
      uses: actions/upload-artifact@v3
      with:
        name: requirements-lock
        path: requirements-lock.txt

    - name: Complete Setup
      id: setup
      run: |
        echo "Setup Complete"

    - name: Check Packages
      if: ${{ !cancelled() && steps.setup.conclusion == 'success' }}
      run: |
        make packages-check

    - name: Check Import Order
      if: ${{ !cancelled() && steps.setup.conclusion == 'success' }}
      run: |
        make import-check

    - name: Check Formatting 
      if: ${{ !cancelled() && steps.setup.conclusion == 'success' }}
      run: |
        make format-check

    - name: Check Lints
      if: ${{ !cancelled() && steps.setup.conclusion == 'success' }}
      run: |
        make lint

    - name: Run Unit Tests With Coverage
      if: ${{ !cancelled() && steps.setup.conclusion == 'success' }}
      run: |
        make test-xml-coverage

    - name: Generate LCOV report
      if: ${{ !cancelled() && steps.setup.conclusion == 'success' }}
      run: |
        make coverage-lcov
        sed -i "s;$PWD/;;g" reports/coverage.lcov

    - name: Publish Reports
      if: ${{ !cancelled() && steps.setup.conclusion == 'success' }}
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: reports/
 
    - name: Publish Unit Test Coverage
      if: ${{ !cancelled() && steps.setup.conclusion == 'success' }}
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: reports/coverage.lcov
        artifact-name: code-coverage-report
        minimum-coverage: 0
        github-token: ${{ secrets.GITHUB_TOKEN }}
        update-comment: true

    - name: Publish Unit Test Results
      if: ${{ !cancelled() && steps.setup.conclusion == 'success' }}
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: |
          reports/TEST-*.xml
