name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Check out the branch
      uses: actions/checkout@v3

    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1

    - name: Set Up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Display Python Version
      run: python -c "import sys; print(sys.version)"

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Upgrade Pip
      run: |
        make upgrade-pip

    - name: Install Dependencies
      run: |
        make install

    - name: Publish Resolved Dependencies
      uses: actions/upload-artifact@v3
      with:
        name: requirements-lock
        path: requirements-lock.txt

    - name: Complete Setup
      id: setup
      run: |
        echo "Setup Complete"

    - name: Build #TODO
      run: python -m py_compile src/main.py

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Download Builds
        uses: actions/download-artifact@v3
        with:
          name: build #TODO
          path: bin #TODO
      - name: Display structure of downloaded files
        run: ls -R
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: bin/*
