name: Upgrade Dependencies

on:
    schedule:
        - cron: '0 13 * * 6'
    workflow_dispatch: # Allow the workflow to be started manually

jobs:
    upgrade-deps:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the branch
              uses: actions/checkout@v3

            - name: Set Up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: 3.10

            - name: Cache pip dependencies
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
                
            - name: Upgrade Dependencies
              run: |
                sed -i 's/==/>=/g' requirements.txt
                python -m pip install --upgrade -r requirements.txt
                python -m pip freeze > requirements.txt

            - name: Check for changes
              id: check_changes
              run: |
                git diff --quiet
                echo "::set-output name=has_changes::$(git diff --quiet || echo true)"

            - name: Exit if no changes
              run: |
                if [ "${{ steps.check_changes.outputs.has_changes }}" != "true" ]; then
                  echo "No changes found. Exiting without creating a pull request."
                  exit 0
                fi

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                token: ${{ secrets.UPDATE_DEPS_TOKEN }}
                base: main
                branch: update-deps
                branch-suffix: timestamp
                commit-message: update-deps
                title: Automated Dependency Upgrade
                body: |
                  Automatic update of dependencies
