name: Upgrade Dependencies

on:
    schedule:
        - cron: '0 13 * * 6'
    workflow_dispatch: # Allow the workflow to be started manually

jobs:
    upgrade-deps:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the branch
              uses: actions/checkout@v3

            - name: Set Up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: "3.10"

            - name: Upgrade Pip
              run: |
                python -m pip install --upgrade pip
                
            - name: Upgrade Dependencies
              run: |
                sed -i 's/==/>=/g' requirements.txt
                python -m pip install --upgrade -r requirements.txt
                python -m pip freeze > requirements.txt

            - name: Print Changes
              run: |
                git diff -U0

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                base: main
                branch: upgrade-dependencies
                branch-suffix: timestamp
                commit-message: upgrade-dependencies
                title: Automated Dependency Upgrade
                body: |
                  Automated dependency upgrade, created by https://github.com/jtfedd/3d-radar/actions/workflows/upgrade_deps.yml
